### ISSUE TITLE
RetroShare won't start anymore "Issues With Private Key! - Doesn't match your Cert"

### ISSUE THREAD

**Issue by whocares0101** [RetroShare/RetroShare#1354]
My RetroShare won't start anymore and there is allegedly a problem with my private key.
"user_cert.pem" and "user_pk.pem" are the same I use since at least 2015 and they haven't changed, I have a backup.

I'm running debian/unstable AMD64.

```
$ gcc --version
gcc (Debian 8.2.0-7) 8.2.0
```

```
$ qmake --version
QMake version 3.1
Using Qt version 5.11.1 in /usr/lib/x86_64-linux-gnu
```

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.
```

```
$ git branch -v
  list   c61ccda43 fixed compilation problem caused by a bug in qtcreator global replace. Warning: always check the result of qtcreator global replace
* master 359e11433 jsonapi-generator add missing include
  show   359e11433 jsonapi-generator add missing include
```

```
RetroShare:: Successfully installed the SIGPIPE Block
Hashed main executable: c71404622675ccbc6fbfa48fa30badf27affcd19
defaultBaseDirectory() = /home/master/.retroshare
(WW) Error in PGPHandler::validateAndUpdateSignatures(). Validation failed for at least some signatures.
Pubring read successfully.
Secring read successfully.
PGPHandler: Successfully read 17c1 trust packets.
RsAccounts::getAvailableAccounts()
(II) Skipping symbolic link /home/master/.retroshare/.retroshare
(II) Skipping symbolic link /home/master/.retroshare/.retrosharepz$
getAvailableAccounts() Skipping Invalid sized dir: extensions6
getAvailableAccounts() Skipping Invalid sized dir: tor_hidden_service
getAvailableAccounts() Skipping Invalid sized dir: pgp
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-master'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-master'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-master'
Rshare::Rshare waitForConnected to other instance.
Rshare::Rshare failed to connect to other instance.
(WW) Clearing PGP passphrase.
(WW) Caching PGP passphrase.
rsAccounts->PathKeyFile() : /home/master/.retroshare/LOC06_<ID>/keys/user_pk.pem
SSL Library Init!
Issues With Private Key! - Doesn't match your Cert
Check your input key/certificate:
/home/master/.retroshare/LOC06_<ID>/keys/user_pk.pem & /home/master/.retroshare/LOC06_<ID>/keys/user_cert.pem
Creating Init File: /home/master/.retroshare/default_cert_06.txt
        Id: <ID>
========================================================================
==                 RsInit:: starting up Retroshare core               ==
==                                                                    ==
== Account/SSL ID        : 00000000000000000000000000000000           ==
== Node type             : Normal                                     ==
========================================================================
main() - Fatal Error.....
Invalid Certificate configuration!

libretroshare failed to startup!
Memory still in use at end of program: 0 bytes.
```

**Comment by ghost** [comment]
I'm having the same issue. Errors out on both used and new accounts as well as after a removal and purge followed by another install.

`Linux sleepy 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux`
```

yuri ~ $ retroshare
RetroShare:: Successfully installed the SIGPIPE Block
Cannot hash executable! Plugins will not be loaded correctly.
defaultBaseDirectory() = /home/yuri/.retroshare
Pubring read successfully.
Secring read successfully.
PGPHandler: Successfully read 0 trust packets.
RsAccounts::getAvailableAccounts()
getAvailableAccounts() Skipping Invalid sized dir: pgp
Rshare::Rshare waitForConnected to other instance.
Rshare::Rshare failed to connect to other instance.
(WW) Clearing PGP passphrase.
(WW) Caching PGP passphrase.
rsAccounts->PathKeyFile() : /home/yuri/.retroshare/LOC06_<<ID>>/keys/user_pk.pem
SSL Library Init!
Issues With Private Key! - Doesn't match your Cert
Check your input key/certificate:
/home/yuri/.retroshare/LOC06_<<ID>>/keys/user_pk.pem & /home/yuri/.retroshare/LOC06_<<ID>>/keys/user_cert.pem
Creating Init File: /home/yuri/.retroshare/default_cert_06.txt
	Id: <<ID>>
main() - Fatal Error.....
Invalid Certificate configuration!

libretroshare failed to startup!
Memory still in use at end of program: 0 bytes.
```

**Comment by G10h4ck** [comment]
How did you got RetroShare for debian unstable? did you compiled it by yourself? if sow which commands did you used?

**Comment by ghost** [comment]
> How did you got RetroShare for debian unstable? did you compiled it by yourself? if sow which commands did you used?

The first install (which worked for a while) was gotten from the apt repo. For the second install I followed the instructions on how to compile it. Note that I got
`E: Unable to locate package libqtmultimediakit1
E: Unable to locate package qtmobility-dev
`
when attempting to download the listed packages. Using the make command spits out 
`Project ERROR: Unknown module(s) in QT: uitools multimedia x11etras
make: *** [Makefile:151: retroshare_gui-make_first] Error 3`

most likely due to packages failing.

**Comment by bmigunov** [comment]
I've got this type of issue after updating openssh & openssl, but still don't know how to solve it.

**Comment by csoler** [comment]
that seems pretty serious. Does it work when you create a new node?

**Comment by ghost** [comment]
> that seems pretty serious. Does it work when you create a new node?

If you mean "New Profile/Node", then yes. I'd post the entire output, but I'm not too sure what to strip from it. It has the two large blocks for RSAPublicKey and Sha1WithRSAEncryption, so it looks like it may be creating it, but I still have the same error at the end and a failure to start.

**Comment by csoler** [comment]
Assuming that you're using the released version 0.6.4, it sounds like there's something in openssl that is changed in your upgraded version. Obviously debian should keep compatibility between minor versions, but it could be that something changed that we don't check because we did n't have to before that, etc. 

I suggest that you do one of these:
- re-compile RS. That would ensure that current SSL version in the RS binary is the one on your system libraries
- downgrade openssl. Generally not a good idea because upgrades usually fix security issues.

Could you tell which  versions of packages openssl are causing these errors, and which version of openssl you had before the upgrade? If it's 0.9.8->1.0.1, no need to look further: RS doesn't use the same code  for both versions, and that is decided at compile time.

thx

**Comment by ghost** [comment]
I'm running `OpenSSL 1.1.1-2 11 Sep 2018`. I cannot compile RS successfully due to packages missing (see above post) and downgrading doesn't seem like a great idea. `apt-cache policy retroshare` returns 0.6.4.

If I can find out how to get those packages listed on the main page installed (libqtmultimediakit1 and qtmobility-dev), I can go ahead and compile it, but not until then. apt tells me that it is unable to locate them. I've attempted downloading the .deb files from the debian package page, but they fail to install due to dependencies.

**Comment by stanclai** [comment]
The same symptoms with “Issues With Private Key! - Doesn't match your Cert”. OS Debian buster/sid, OpenSSL: libssl1.1 version 1.1.1-2
Versions of RS:
- 0.6.4-1.20180601.6bb1d3c5~**artful** (from ppa) **still works**
- 0.6.4-1.20180904.703d7096~bionic (from ppa) doesn't work
- 0.6.4-1.20180910.c17b821e~sid (compiled on my system) doesn't work
- 0.6.4-1.20181024.966cd27c~sid (compiled on my system) doesn't work

Custom binaries were built without issues and were installed from .deb packages.

I made diff of `ldd retroshare` output for each of mentioned binaries and main difference was in libssl version: **artful** uses **libssl.so.1.0.0** and all **others** use **libssl.so.1.1**. So I guess @csoler was right about something wrong with new OpenSSL support.

**Comment by stanclai** [comment]
well… :) I've just succeeded to build relatively [fresh RS version](https://github.com/RetroShare/RetroShare/commit/69debe5052e062851a0cb075f040c2b0b55768d9) on Debian Sid using libssl1.0. so, I have native Debian package linked with old ssl version which can be still found in Sid repo (libssl1.0-dev and libssl1.0.2, which are actually 1.0.2q-2). and it works like a charm. but if I build all by default without changes, it uses libssl 1.1 and I have broken application giving me the error mentioned in this issue topic.

so, further are some

### thoughts on resolving the problem
as far as I can understand, this is not RS issue in itself, but rather consequences of [libssl upgrade](https://git.openssl.org/?p=openssl.git;a=commit;h=9e8b6f042749ded556380227c9f2db7ffad9a3aa) which broke backward compatibility: version **1.1** uses **sha256** hash by default while **1.0** uses **md5**. therefore (I'm not absolutely sure, though) new versions of RS try to handle existing keys made with old libssl version and can't verify them, 'cos it uses different hash. if this is an issue, then, maybe it would make sense to check keys with both hashes (if it's not possible to distinguish between old and new versions of the keys)? or, if version info is present in key metadata, is it possible to work with old keys using md5?

@csoler, @G10h4ck, is this opinion reasonable from your pov and is it worth to implement it?

**Comment by G10h4ck** [comment]
Any PR solving this issue would be welcome!

**Comment by jowakr** [comment]
I had the same problem in Debian Buster. Here is what I found out:

1. Debian increased the default security level for OpenSSL from 1 to 2. See the openssl [changelog](https://metadata.ftp-master.debian.org/changelogs//main/o/openssl/openssl_1.1.1b-1_changelog) (version `1.1.1~~pre6-1`). 
2. In the OpenSSL [documentation](https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_security_level.html), you can see that this requires 112 bit of security instead of 80 bit.
3. In the OpenSSL [source code](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1/crypto/x509/x509_set.c), you can see, that it defines the security of the signature digest for the certificate as half the number of bits that the signature algorithm has (comment in line 223: `Security bits: half number of bits in digest`). SHA1 is 160 bit wide and is therefore considered to only provide 80 bit of security and will fail the security level 2 check.

The issue isn't that hard to work around: there is a config file `/etc/ssl/openssl.cnf` that defines the default OpenSSL settings and is provided by Debian. The security level is set at the end of the file (`CipherString = DEFAULT@SECLEVEL=2`). RetroShare will work again, if this is reduced to 1.

Another (probably better) possibility is to set the `OPENSSL_CONF` environment variable to an empty string when starting RetroShare. Then it won't pick up the default config file and run with the OpenSSL default security level of 1.

I'm not sure, what the "proper" fix would look like. I guess new certificates should be generated using SHA256, but RetroShare will still have to accept certificates of other nodes and handle old certificates. One possibility would probably be to set the security level explicitly from the code using `SSL_CTX_set_security_level` at several places.

**Comment by csoler** [comment]
it seems to me that openssl is refusing SHA1 signatures in certificates. You can safely enable non backward compatible changes 01,02 and 03 (in .pro) and make clean+make, to have RS use SHA256 for PGP signature in certificates. Then create a new location with your certificate.  RS nodes not older than nov 2017 should still connect to you.

**Comment by csoler** [comment]
Please see https://github.com/RetroShare/RetroShare/pull/1752. Test it and report to me.
Unfortunately I cannot test myself since the SSL_CTX_set_security_level() is not present on 1.1.1 on my own system.

**Comment by csoler** [comment]
PR #1768 should fix it.

**Comment by csoler** [comment]
I merged it. The only catch is that if you create a new identity on a debian buster, the cert will be SHA256-signed and therefore will work with security level 2, but security level 2 will prevent you from cnonnecting to friends with SHA1-signed certificates.

**Comment by G10h4ck** [comment]
Better keep them open until we release the fix, and then close them and remove the "Fixed but not released" flag. This should reduce bug duplication.

**Comment by felisucoibi** [comment]
the problem is still there with latest build, i cant use my original user anymore
k.pem
SSL Library Init!
(EE) Cannot use your Retroshare certificate. Some error occured in SSL_CTX_use_certificate()
Creating Init File: xxxxx
	Id: xxxx
(WW) Clearing PGP passphrase.
getRetroshareDataDirectory() found: /usr/share/retroshare
getRetroshareDataDirectory() found: /usr/share/retroshare
========================================================================
==                 RsInit:: starting up Retroshare core               ==
==                                                                    ==
== Account/SSL ID        : 00000000000000000000000000000000           ==
== Node type             : Normal                                     ==
========================================================================
main() - Fatal Error.....
Invalid Certificate configuration!

libretroshare failed to startup!
Memory still in use at end of program: 0 bytes.

**Comment by shibe2** [comment]
I have this problem when trying to use my existing account.
RetroShare 0.6.6
OpenSSL 3.0.7

RetroShare says:

    (EE) Cannot use your Retroshare certificate. Some error occured in SSL_CTX_use_certificate()

OpenSSL says:

    40F2AB76B37F0000:error:0A00018E:SSL routines:SSL_CTX_use_certificate:ca md too weak:ssl/ssl_rsa.c:221:

**Comment by csoler** [comment]
Hi. This is because OpenSSL > 3 has a security level that forbits SHA1-signed certificates. So SSL_CTX_use_certificate() returns an error. Your options are:
1 - use the current master branch of RS (compile it, etc). It includes a bypass, but this may not work everytime. It works on ubuntu 20.04 but not 22.04 where openssl is too restrictive.
2 - create a new location (using the same certificate). Your friends will still accept you. you only need to re-add them on your side.
